#!/usr/bin/env bash

# Display a list of currently running processes with user-oriented format and hierarchy
echo "List of currently running processes:"

# Use 'ps' command to display the processes
ps aux --forest
